config/routes.rb
Rails.application.routes.draw do

  get '/register',to: 'home#register'
  get '/login',to: 'home#login'
  root to: 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, format:{ with:/\A[^@\S]+@[^@\S]+\Z/, message:"must be a valid email address"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def register
    flash.now[:notice]="Registered Successfully"
  end
  def login
    flash.now[:notice]="Logged in Successfully"
  end
  def page
  end
end

app/controllers/user_controller.rb
class UserController <ApplicationController
  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="jumbotron centered">
  <div class="container">
    <i class="fas fa-key fa-6x"></i>
    <h1 class="display-3">Discourse WebPage</h1>
    <p class="lead">Key to Success !!!</p>
    <hr>
    <%= link_to 'Register' , register_path , class:'btn btn-light btn-lg' %>
    <%= link_to 'login' , login_path , class:'btn btn-dark btn-lg' %>
    <hr>
    <button type="submit" class="btn btn-dark">SignUp for free</button>
  </div>
</div>

app/views/home/login.html.erb
<div class="container mt-5">
  <h1>Login</h1>

  <div class="row">
    <div class="col-sm-8">
      <div class="card">
        <div class="card-body">

          <form action="/login-successful" method="POST">
            <div class="form-group">
              <label for="email">Email</label>
              <input type="email" class="form-control" name="username">
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" name="password">
            </div>
            <button type="submit" class="btn btn-dark">Login</button>
          </form>

        </div>
      </div>
    </div>

  </div>
</div>

app/views/home/mainPage.html.erb
<div class="alert alert-dark" role="alert">
  <%= render partial:"shared/flash" %>
</div>

~~ This will be our main PostingWebsite

app/views/home/register.html.erb
<div class="container mt-5">
  <h1>Register</h1>

  <div class="row">
    <div class="col-sm-8">
      <div class="card">
        <div class="card-body">

          <form action="/registered_succesfully" method="POST">
            <div class="form-group">
              <label for="email">Email</label>
              <input type="email" class="form-control" name="username">
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" name="password">
            </div>
            <button type="submit" class="btn btn-dark">Register</button>
          </form>

        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>First</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
     
  </head>

  <body>
    <%= yield %>  <!--This is the views>home>index  file-->
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
  <%= flash[:notice]%>
<%end%>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_with(model: @user, local: true) do |f| %>

<div class="form-group">
  <%= f.label :email %><br/>
  <%= f.email_field :email, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :password %><br/>
  <%= f.password_field :password, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.submit %>
</div>

<% end %>